import type { Metadata } from "next";
import "./globals.css";
import { body, heading } from "@/lib/fonts";
import Navbar from "./_modules/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${body.className} ${heading.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
